### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by smithgb** [veevickytoria/Section04#88]
@harrissa @millerns @someoneseth @Paulbliudzius @yuhasem @dgart01 

How are notifications being implemented in the backend? Also, are "push notifications" a thing?

**Comment by smithgb** [comment]
I just looked at the API and found the call you implemented for notifications. Can the front ends assume that the backend will manage whether or not certain notifications are read/unread? All we should have to do is pull the notifications from the DB and display them?

**Comment by shahdk** [comment]
The way push notifications work, atleast for iOS, is that our server will notify Apple's server which will then notify the device. We cannot really do DB calls when the app is not running, which is why there are push notifications because even if your app is not running, the apple server will notify the device on the given date and time.

**Comment by smithgb** [comment]
How do the front ends know which notifications are new when we grab them?

**Comment by gamescoot** [comment]
Just grab them with checkNotifications for now... Notifications are hard. We're talking about how to design them properly right now.

**Comment by gamescoot** [comment]
Also, I think we should delete old notifications... But I'm not sure about that.

**Comment by gamescoot** [comment]
I'm closing this issue until Notifications is properly implemented in next sprint. Feel free to reopen it or post a new issue.
